spring:
  application:
    name: healthcare-pre-authorization
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/healthcare_preauth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: dbuser
    password: dbpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      data-locations: classpath:sql/member-data.sql, classpath:sql/provider-data.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
